{{ if and .Values.ingress.tls.enabled .Values.ingress.enabled }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Values.ingress.hostName }}-cert
spec:
  secretName: {{ .Values.ingress.hostName }}-cert
  issuerRef:
    name: {{ .Values.ingress.tls.clusterIssuer }}
  commonName: {{ .Values.ingress.hostName }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ .Values.ingress.hostName }}
{{ end }}