apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-{{ .Release.Revision }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Release.Name }}-{{ .Release.Revision }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Release.Name }}-{{ .Release.Revision }}
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: docroot
      volumes:
      - name: docroot
        hostPath:
          path: {{ .Values.content.root }}
          type: DirectoryOrCreate