{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-{{ .Release.Revision }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{ if .Values.ingress.tls.enabled }}
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.tls.clusterIssuer}}
    {{ end }}
spec:
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}-{{ .Release.Name }}-{{ .Release.Revision }}
          servicePort: 80
  {{ if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostName }}
    secretName: {{ .Values.ingress.hostName }}-cert
  {{ end }}
{{ end }}