apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-{{ .Release.Revision }}
  labels:
    app: {{ .Chart.Name }}-{{ .Release.Name }}-{{ .Release.Revision }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}-{{ .Release.Name }}-{{ .Release.Revision }}
