email: test@example.com

staging:
  name: letsencrypt-staging
  server: https://acme-staging-v02.api.letsencrypt.org/directory
  ingressClass: nginx

prod:
  name: letsencrypt-prod
  server: https://acme-v02.api.letsencrypt.org/directory
  ingressClass: nginx